<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\filesystem\\abstractdirectorytestbase' => '/AbstractDirectoryTestBase.php',
                'spriebsch\\filesystem\\existingdirectorytest' => '/ExistingDirectoryTest.php',
                'spriebsch\\filesystem\\fakedirectorytest' => '/FakeDirectoryTest.php',
                'spriebsch\\filesystem\\filegetcontents' => '/FileSeparateTest.php',
                'spriebsch\\filesystem\\fileseparatetest' => '/FileSeparateTest.php',
                'spriebsch\\filesystem\\filesystemexceptiontest' => '/FilesystemExceptionTest.php',
                'spriebsch\\filesystem\\filesystemtest' => '/FilesystemTest.php',
                'spriebsch\\filesystem\\filetest' => '/FileTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
